name: budz_app
description: 'Projeto flutter para o teste técnico da Budz'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  logger: ^2.4.0
  flutter_screenutil: ^5.9.3

  get_cli: ^1.8.1

  shared_preferences: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.3.0
  rename_app: ^1.6.1

  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0
  http: ^1.2.2

  url_launcher: ^6.3.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.3.3
  json_serializable: ^6.5.4

  carousel_slider: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/data/budz_home.json
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
